= How to add Libbulletjme to an existing project
:Project: Libbulletjme
:experimental:
:page-pagination:
:url-api: https://stephengold.github.io/Libbulletjme/javadoc/master/com/jme3/bullet
:url-enwiki: https://en.wikipedia.org/wiki
:url-tutorial: https://github.com/stephengold/LbjExamples/blob/master/apps/src/main/java/com/github/stephengold/lbjexamples/apps

Adding {Project} to an existing Java project is a 7-step process:

. Add the Java library to the classpath.
. Download an appropriate native library.
. Load the native library.
. Create and configure a physics space.
. Create and configure collision objects
  and add them to the physics space.
. Simulate the physics space.
. Test and tune as necessary.

== Add Java library to classpath

=== Gradle-built projects

Add to the project's "build.gradle" file:

[source,groovy]
----
repositories {
    mavenCentral()
}
dependencies {
    implementation 'com.github.stephengold:Libbulletjme:15.1.0'
}
----

For some older versions of Gradle,
it's necessary to replace `implementation` with `compile`.

=== Maven-built projects

Add to the project's "pom.xml" file:

[source,xml]
----
<repositories>
    <repository>
      <id>mvnrepository</id>
      <url>https://repo1.maven.org/maven2/</url>
    </repository>
</repositories>

<dependency>
  <groupId>com.github.stephengold</groupId>
  <artifactId>Libbulletjme</artifactId>
  <version>15.1.0</version>
</dependency>
----

=== Ant-built projects

Download the {Project} library from GitHub:

* https://github.com/stephengold/Libbulletjme/releases/latest

You'll want the class JAR ("Libbulletjme-15.1.0.jar")
and probably the "-sources" and "-javadoc" JARs as well.

Open the project's properties in the NetBeans IDE:

. Right-click on the project (not its assets) in the "Projects" window.
. Select menu:Properties[] to open the "Project Properties" dialog.
. Under "Categories:", click on btn:[Libraries].
. Click on the btn:[Compile] tab.
. Add the Heart class JAR:
.. Click on the btn:[Add JAR/Folder] button.
.. Navigate to the download directory.
.. Select the "Libbulletjme-15.1.0" file.
.. Click on the btn:[Open] button.
. (optional) Add JARs for javadoc and sources:
.. Click on the btn:[Edit] button.
.. Click on the btn:[Browse...] button to the right of "Javadoc:"
.. Select the "Libbulletjme-15.1.0-javadoc.jar" file.
.. Click on the btn:[Open] button.
.. Click on the btn:[Browse...] button to the right of "Sources:"
.. Select the "Libbulletjme-15.1.0-sources.jar" file.
.. Click on the btn:[Open] button button again.
.. Click on the btn:[OK] button to close the "Edit Jar Reference" dialog.
. Click on the btn:[OK] button to exit the "Project Properties" dialog.

== Download a native library

Pre-built native libraries can be downloaded from GitHub:

* https://github.com/stephengold/Libbulletjme/releases/latest

You don't need all 56 native libraries.
Start with the "DebugSp" library for your development environment,
for instance:

* "Linux64DebugSp_libbulletjme.so" for Linux on x86_64
* "Windows64DebugSp_libbulletjme.so" for 64-bit Windows

== Load the native library

Load Libbulletjme's native library before instantiating any physics objects:

[source,java]
----
import com.jme3.system.NativeLibraryLoader;
NativeLibraryLoader.loadLibbulletjme(true, downloadDirectory, "Debug", "Sp");
----

== Create a physics space

There are many constructors and options.
Here's the simplest way:

[source,java]
----
import com.jme3.bullet.PhysicsSpace;
PhysicsSpace physicsSpace = new PhysicsSpace(PhysicsSpace.BroadphaseType.DBVT);
----

== Create and add objects

Collision objects come in many different types:

* bodies (`PhysicsBody`)
** soft bodies (`PhysicsSoftBody`)
** rigid bodies (`PhysicsRigidBody`)
*** vehicles (`PhysicsVehicle`)
* ghost objects (`PhysicsGhostObject`)
* characters (`PhysicsCharacter`)
* colliders (`MultiBodyCollider`)

Here's a code fragment that creates 2 objects, a ghost object and a rigid body
that share a common shape:

[source,java]
----
float radius = 2f;
CollisionShape sphere2 = new SphereCollisionShape(radius);
PhysicsGhostObject ghost1 = new PhysicsGhostObject(sphere2);
float mass = 1f;
PhysicsRigidBody body1 = new PhysicsRigidBody(sphere2, mass);
----

Collision objects aren't simulated unless they're added to a physics space.
The best way is to use `addCollisionObject()`:

[source,java]
----
physicsSpace.addCollisionObject(ghost1);
physicsSpace.addCollisionObject(body1);
----

== Simulate the physics space

To simulate a single 20-millisecond time step:

[source,java]
----
float timeStep = 0.02f; // in seconds
physicsSpace.update(timeStep, 0);
----

In real-time simulation, the interval between updates will vary.
However, it's best to use steps of equal size.

To attempt simulation of a specific time interval
using the configured step size:

[source,java]
----
physicsSpace.update(intervalSeconds);
----

== HelloLibbulletjme

{url-tutorial}/console/HelloLibbulletjme.java[HelloLibbulletjme]
is a complete console application (no graphics)
that serves as a starting point for using Libbulletjme.

It illustrates:

. loading a native library from the "~/Downloads" directory
. creating a `PhysicsSpace`
. creating 2 collision objects and adding them to the space
. running the simulation for 50 time steps

[IMPORTANT]
====
`HelloLibbulletjme` is the first in a series of
tutorial apps designed for hands-on learning.
I expect you to not only study the source code,
but to actually run the app as well.
Take time *now* to set up a
{url-enwiki}/Integrated_development_environment[software development environment]
for this purpose!

For instance, if you install Git and a Java Development Kit,
you should be able to launch tutorial apps from a command shell, like so:

. `git clone https://github.com/stephengold/LbjExamples.git`
. `cd LbjExamples`
. `./gradlew HelloLibbulletjme`

====

== Summary

* Two libraries are required: a Java library and a native library.
* Collision objects aren't simulated unless they're added to a space.
