= Libbulletjme project overview
:Project: Libbulletjme
:url-enwiki: https://en.wikipedia.org/wiki

_{Project}_ is a 3-D {url-enwiki}/Physics_engine[physics simulation] library
for {url-enwiki}/Java_(programming_language)[Java].

Use it to:

* add solidity to walls, characters, projectiles, landscapes, and vehicles,
* detect collisions between complex shapes,
* perform contact, ray, and sweep tests,
* simulate characters and buildings collapsing in real time, and
* simulate cloth, rope, and deformable volumes,
  including their interactions with rigid bodies and each other.

Tutorials and example apps are provided to help you get started.

All software in the {Project} project is free and open-source,
including the JVM library, the native libraries, the demo and tutorial apps,
and the software used to build, test, and run them.

The underlying simulation software comes from
https://pybullet.org/wordpress[_Bullet_], a mature real-time physics simulator.
But although Bullet is written in {url-enwiki}/C%2B%2B[C&#43;&#43;],
you won't need any knowledge of C&#43;&#43; to use {Project}.

Libbulletjme also incorporates source code from
https://github.com/kmammou/v-hacd[the V-HACD project] and
https://github.com/Simsilica/SimMath[the SimMath library].

== Caveats

{Project}'s focus is on simulating
{url-enwiki}/Classical_mechanics[classical mechanics]
in just enough detail to add verisimilitude to 3-D games.
It's not intended for 2-D {url-enwiki}/Platform_game[platformers],
nor for scientific research.
For 2-D physics, consider using http://www.dyn4j.org/[dyn4j] instead.

{Project} and its documentation
assume a certain level of proficiency with
the Java programming language.
This project isn't aimed at non-programmers,
nor developers without prior Java experience.
Similarly, some familiarity with 3-D graphics and vector math is assumed.

While an understanding of classical mechanics is assumed,
many of its technical terms are linked (at first use)
to the relevant article in the English Wikipedia.

https://raw.githubusercontent.com/stephengold/Libbulletjme/master/LICENSE[The library's mixed open-source license]
disclaims liability for defects.
Please don't use this software in safety-critical applications.

Starting with version 16.1.0,
{Project} is no longer compatible with the older versions of "libc"
found on systems such as CentOS 7 and Ubuntu Xenial 16.04.


== What's missing

Bullet is a large project, and
Libbulletjme doesn't yet provide access to all of its features.
In particular:

* `btRigidBodyConstructionInfo`
* "additional damping" for rigid bodies
* Bullet's debug drawer (but see the SPORT graphics engine in LbjExamples)
* serialization (file loader)
* certain constraints:
** `btFixedConstraint`
** `btUniversalConstraint`
* certain collision shapes:
** `btCompoundFromGimpactShape`
** `btConvexPointCloudShape`
** `btConvexTriangleMeshShape`
** `btGImpactCompoundShape`
** `btMinkowskiSumShape`
** `btMultimaterialTriangleMeshShape`
** `btScaledBvhTriangleMeshShape`
** `btSdfCollisionShape`
** `btTriangleShape`
** `btUniformScalingShape`
* certain world types:
** `btSimpleDynamicsWorld`
** `btSoftMultiBodyDynamicsWorld`
* inverse dynamics
* Bullet v3
* Bullet extras, examples, and tests (but see the Java examples in LbjExamples)

Furthermore, Libbulletjme hasn't yet been ported to the following platforms:

* the FreeBSD and iOS operating systems
* Windows on ARM architectures
* PowerPC architectures

We welcome suggestions concerning the future development of Libbulletjme.


== Getting help

For self-help, make use of
xref:add.adoc[the tutorials],
https://stephengold.github.io/Libbulletjme/javadoc/master[the javadoc], and
https://github.com/stephengold/Libbulletjme[the source code].

For issues that are best handled privately, contact Stephen by e-mail.
His personal e-mail address appears
on https://stephengold.github.io/[his homepage] and in the source code.


== The name

The project's (somewhat awkward) name
reflects that fact that it was originally created
for the JMonkeyEngine (JME) game engine.

Despite its history, Libbulletjme is self-contained;
it doesn't depend on JME.
If you're seeking a physics engine that's integrated with JME,
please consider https://stephengold.github.io/Minie[Minie].


== Next steps

If you're curious how {Project} works,
proceed to xref:implementation.adoc[the Implementation page].

To gain hands-on experience,
proceed to xref:add.adoc[the first tutorial page].
