---
# GitHub Actions workflow for commits pushed to the LbjExamples repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1.0.4
      - run: wget https://github.com/stephengold/Libbulletjme/releases/download/14.3.0/Linux64ReleaseSp_libbulletjme.so
      - run: mkdir ~/Downloads
      - run: mv Linux64ReleaseSp_libbulletjme.so ~/Downloads
      - run: ./gradlew run --console=plain --no-daemon

  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - run: wget https://github.com/stephengold/Libbulletjme/releases/download/14.3.0/MacOSX64ReleaseSp_libbulletjme.dylib
      - run: mv MacOSX64ReleaseSp_libbulletjme.dylib ~/Downloads
      - run: ./gradlew run --console=plain --no-daemon
