---
# GitHub Actions workflow for commits pushed to the LbjExamples repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java8-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - uses: actions/checkout@v4
      - run: ./gradlew javadoc --console=plain --stacktrace
      - run: ./gradlew :apps:HelloLibbulletjme --console=plain --stacktrace
      - run: ./gradlew :apps:HelloVehicle0 --console=plain --stacktrace

  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - run: mkdir ~/Downloads
      - run: ./gradlew javadoc --console=plain --stacktrace
      - run: ./gradlew :apps:HelloLibbulletjme --console=plain --stacktrace
      - run: ./gradlew :apps:HelloVehicle0 --console=plain --stacktrace

  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-14
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v4
      - run: ./gradlew javadoc --console=plain --stacktrace
      - run: ./gradlew :apps:HelloLibbulletjme --console=plain --stacktrace
      - run: ./gradlew :apps:HelloVehicle0 --console=plain --stacktrace

  Java21-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - run: ./gradlew javadoc --console=plain --stacktrace
        shell: bash
      - run: ./gradlew :apps:HelloLibbulletjme --console=plain --stacktrace
        shell: bash
      - run: ./gradlew :apps:HelloVehicle0 --console=plain --stacktrace
        shell: bash
