---
# GitHub Actions workflow for commits pushed to the LbjExamples repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java8-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      - run: ./gradlew :apps:HelloVehicle0 --console=plain --no-daemon --stacktrace
        shell: bash

  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1.0.4
      - run: mkdir ~/Downloads
      - run: ./gradlew :apps:HelloLibbulletjme --console=plain --no-daemon --stacktrace
      - run: ./gradlew :apps:HelloVehicle0 --console=plain --no-daemon --stacktrace

  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew :apps:HelloLibbulletjme --console=plain --no-daemon --stacktrace
      - run: ./gradlew :apps:HelloVehicle0 --console=plain --no-daemon --stacktrace

  Java17-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew :apps:HelloLibbulletjme --console=plain --no-daemon --stacktrace
      - run: ./gradlew :apps:HelloVehicle0 --console=plain --no-daemon --stacktrace
        shell: bash
